### ISSUE TITLE
Decent Authentication

### ISSUE THREAD

**Issue by FelixVanderJeugt** [ZeusWPI/slotmachien#33]
Slotmachien may have begun as some kind of experiment, but if we wish to keep using it, we need it to be solid and usable. It is not now. I propose the following change to get it in the right direction:

There must be one single list of slotmachien users. At the moment, you have
 - The whitelist on the web api
 - The tokens on the web api (each having multiple users)
 - The people knowing the password of the raspberry pi
 - The people in the `slotmachien` Kerberos user group through wells.

This is clearly too much. Imagine taking the access to slotmachien. You'd have to remove this user from two lists, remove every token/password he might know, and inform all other users their token/password was changed. Not very good.

So, one single list of users. First of all, I'd put a ban on the web tokens. This is useful for services like slack, but not trackable if you give them to users, or put them in the mobile app. The password on the rpi, nope. First of all, it's too easy at the moment. Second, it's not usable, you have to ssh twice if you're not on the local network. So we should change this password to the client/admin password and forget about sharing it.

Thus, it's between the whitelist on the api and the group on Kerberos. Now the whitelist on the web api is usable only through slack. After all, it assumes the service has a token and does not lie about it's usernames. So only one choice remains: Kerberos.

Now how to use this with the app and the web api and stuff. That's for my next comment, first some stuff to do.

**Comment by feliciaan** [comment]
Started using Zeus OAuth, so can be closed.
