### ISSUE TITLE
Delayed close is reverted immediately

### ISSUE THREAD

**Issue by ninewise** [ZeusWPI/slotmachien#65]
I just tried closing the door with the delayed close button. As usual, I heard the door lock while I was walking away; a zooming rotation followed by a powerful *click*. However, immediately afterwards, I heard the same sound again. Zoom. *Click*. I went back, checked and the door was unlocked. I opened the door, pressed the delayed close button, waited. Bleep. Bleep. Bleep. Bleep. Bleep. Bleep. Bleep. Bleep. Bleep. Bleep. Bleep. Zoom. *Click*. Zoom. *Click*. The door locked, only to unlock right away. I locked the door with my key and came here to report.

Plz fix.

**Comment by fbegyn** [comment]
This has been happening for a couple of weeks now even across multiple reboots. A reboot temporarily resolves this issue.

**Comment by werthen** [comment]
My hypothesis is that the contacts connecting the motors to the main brick aren't providing enough power (corrosion/slijtage?). I am going to look into it tomorrow on the codenight

**Comment by redfast00** [comment]
Fixed with SlotMachIIn
